spring:
  datasource:
    url: jdbc:oracle:thin:@oracle:fiap:com:br:1521:ORCL
    username:
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update