spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521/ORCL
    username: rm552425
    password: 140904
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update